# Form implementation generated from reading ui file 'D:\onedrive\document\PythonDocument\PyQt6ToImprovement\ArticleMaterial\PyQt6\chapter6\signals_slots\ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 296)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton9 = QtWidgets.QPushButton(parent=Form)
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout.addWidget(self.pushButton9, 1, 2, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 2, 0, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setStyleSheet("font: 22pt;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.pushButton8 = QtWidgets.QPushButton(parent=Form)
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.pushButton8, 1, 1, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(parent=Form)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 1, 0, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(parent=Form)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 2, 2, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(parent=Form)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 3, 0, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 3, 1, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 3, 2, 1, 1)
        self.pushButtonClear = QtWidgets.QPushButton(parent=Form)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.gridLayout.addWidget(self.pushButtonClear, 4, 0, 1, 1)
        self.pushButton0 = QtWidgets.QPushButton(parent=Form)
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout.addWidget(self.pushButton0, 4, 1, 1, 1)
        self.pushButtonback = QtWidgets.QPushButton(parent=Form)
        self.pushButtonback.setObjectName("pushButtonback")
        self.gridLayout.addWidget(self.pushButtonback, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton7, self.pushButton8)
        Form.setTabOrder(self.pushButton8, self.pushButton9)
        Form.setTabOrder(self.pushButton9, self.pushButton4)
        Form.setTabOrder(self.pushButton4, self.pushButton5)
        Form.setTabOrder(self.pushButton5, self.pushButton6)
        Form.setTabOrder(self.pushButton6, self.pushButton1)
        Form.setTabOrder(self.pushButton1, self.pushButton2)
        Form.setTabOrder(self.pushButton2, self.pushButton3)
        Form.setTabOrder(self.pushButton3, self.pushButton0)
        Form.setTabOrder(self.pushButton0, self.pushButtonClear)
        Form.setTabOrder(self.pushButtonClear, self.pushButtonback)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "界面设计与功能实现分开"))
        self.pushButton9.setText(_translate("Form", "9"))
        self.pushButton4.setText(_translate("Form", "4"))
        self.pushButton5.setText(_translate("Form", "5"))
        self.pushButton8.setText(_translate("Form", "8"))
        self.pushButton7.setText(_translate("Form", "7"))
        self.pushButton6.setText(_translate("Form", "6"))
        self.pushButton1.setText(_translate("Form", "1"))
        self.pushButton2.setText(_translate("Form", "2"))
        self.pushButton3.setText(_translate("Form", "3"))
        self.pushButtonClear.setText(_translate("Form", "清除"))
        self.pushButton0.setText(_translate("Form", "0"))
        self.pushButtonback.setText(_translate("Form", "后退"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
