# Form implementation generated from reading ui file 'D:\onedrive\document\PythonDocument\PyQt6ToImprovement\ArticleMaterial\PyQt6\chapter23\ledger\DialogChargeClassification.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCharge(object):
    def setupUi(self, DialogCharge):
        DialogCharge.setObjectName("DialogCharge")
        DialogCharge.resize(321, 635)
        DialogCharge.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogCharge)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ChargeClassificationTree = QtWidgets.QTreeView(parent=DialogCharge)
        self.ChargeClassificationTree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.ChargeClassificationTree.setObjectName("ChargeClassificationTree")
        self.verticalLayout.addWidget(self.ChargeClassificationTree)

        self.retranslateUi(DialogCharge)
        QtCore.QMetaObject.connectSlotsByName(DialogCharge)

    def retranslateUi(self, DialogCharge):
        _translate = QtCore.QCoreApplication.translate
        DialogCharge.setWindowTitle(_translate("DialogCharge", "选择合适的支出分类"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogCharge = QtWidgets.QDialog()
    ui = Ui_DialogCharge()
    ui.setupUi(DialogCharge)
    DialogCharge.show()
    sys.exit(app.exec())
