# Form implementation generated from reading ui file 'D:\onedrive\document\PythonDocument\PyQt6ToImprovement\ArticleMaterial\PyQt6\chapter23\ledger\DialogAccount.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Account(object):
    def setupUi(self, Dialog_Account):
        Dialog_Account.setObjectName("Dialog_Account")
        Dialog_Account.resize(320, 408)
        Dialog_Account.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Account)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AccountTree = QtWidgets.QTreeView(parent=Dialog_Account)
        self.AccountTree.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.AccountTree.setObjectName("AccountTree")
        self.verticalLayout.addWidget(self.AccountTree)

        self.retranslateUi(Dialog_Account)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Account)

    def retranslateUi(self, Dialog_Account):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Account.setWindowTitle(_translate("Dialog_Account", "请选择合适的账户"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Account = QtWidgets.QDialog()
    ui = Ui_Dialog_Account()
    ui.setupUi(Dialog_Account)
    Dialog_Account.show()
    sys.exit(app.exec())