# Form implementation generated from reading ui file 'D:\onedrive\document\PythonDocument\PyQt6ToImprovement\ArticleMaterial\PyQt6\chapter23\ledger\DialogPwd.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_pwd(object):
    def setupUi(self, Dialog_pwd):
        Dialog_pwd.setObjectName("Dialog_pwd")
        Dialog_pwd.resize(400, 122)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_pwd)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog_pwd)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog_pwd)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkBox_showPWD = QtWidgets.QCheckBox(parent=Dialog_pwd)
        self.checkBox_showPWD.setObjectName("checkBox_showPWD")
        self.verticalLayout.addWidget(self.checkBox_showPWD)
        self.label_2 = QtWidgets.QLabel(parent=Dialog_pwd)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(parent=Dialog_pwd)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=Dialog_pwd)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_pwd)
        QtCore.QMetaObject.connectSlotsByName(Dialog_pwd)

    def retranslateUi(self, Dialog_pwd):
        _translate = QtCore.QCoreApplication.translate
        Dialog_pwd.setWindowTitle(_translate("Dialog_pwd", "输入密码"))
        self.label.setText(_translate("Dialog_pwd", "密码："))
        self.checkBox_showPWD.setText(_translate("Dialog_pwd", "显示密码"))
        self.label_2.setText(_translate("Dialog_pwd", "默认密码为空，直接单击“确定”按钮进入！"))
        self.pushButton_ok.setText(_translate("Dialog_pwd", "确定"))
        self.pushButton_cancel.setText(_translate("Dialog_pwd", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_pwd = QtWidgets.QDialog()
    ui = Ui_Dialog_pwd()
    ui.setupUi(Dialog_pwd)
    Dialog_pwd.show()
    sys.exit(app.exec())
